### ISSUE TITLE
Contact us page need a send email button 

### ISSUE THREAD

**Issue by sylarcp** [sylarcp/anita#35]
Follow the example in static/inspinia/landing.html. Add an email button that link to sylarcp@udel.edu.
Also hide all the buttons and selections on the top of contactus page.
For example: $('#connect').hide();

**Comment by dseckel** [comment]
where can i test - not visible on peng's desktop  .125

**Comment by mcollins12321** [comment]
Make sure Peng has merged it with the main code first. Until then its only
in my code.

**Comment by sylarcp** [comment]
The standard solution is letting Mat and Victor have their own servers.  Each time when they push the change, the server will auto deploy the code and restart the website. But for now, I will just merge the code and fix if anything goes wrong.

**Comment by dseckel** [comment]
although i'm a "developer", y'all should consider me to be a user. i want to know when 
you've put something on a user accessible machine.

eventually there should be a released version running on gse-2 (i think) which is always 
up. then there should be a development version, mostly up, but available to testers and 
developers. think of me as a tester.

**Comment by sylarcp** [comment]
I have merged the code and restart the website on 125.   Please also hide the buttons on contact us.

**Comment by varriaza** [comment]
I had a dentists appointment this morning but have been trying to get the buttons hidden since I returned. Unfortunately neither .hide() or .visibility or .display is making anything disappear. I have been primarily putting the code right after "$(document).ready(function () {" but even tried putting it in a few other places. If you know any quick hints, that would be nice. I will keep looking.

**Comment by varriaza** [comment]
I have managed to recreate the base.html without the extra buttons for the contact us page since the easy functions were not working.
